{% set name = "agate-stats" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/agate-stats-{{ version }}.tar.gz
  sha256: dfc863b09033a4b808dfddf6304c24800a0446f1f9c44ba1ffc8a78fc6e6a8da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - agate >=1.5.0

test:
  imports:
    - agatestats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://agate-stats.readthedocs.org/
  summary: agate-stats adds additional statistical methods to agate.
  license: MIT
  license_file: COPYING
  doc_url: http://agate-stats.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-stats

extra:
  recipe-maintainers:
    - pmlandwehr
