{% set name = "agate-stats" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/agate-stats-{{ version }}.tar.gz
  sha256: 9e5455d57d2bb0f24a4e48dce1332f2f6e0cd78e519aa6da0cd329880a52193e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - agate >=1.5.0

test:
  imports:
    - agatestats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://agate-stats.readthedocs.org/
  summary: agate-stats adds additional statistical methods to agate.
  license: MIT
  license_file: COPYING
  doc_url: http://agate-stats.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-stats

extra:
  recipe-maintainers:
    - pmlandwehr
