{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/agate-stats/agate-stats-{{ version }}.tar.gz
  sha256: f1c68a99ffe1dfe2e71a0b9812e374bf5b3768a69ed340bfdec5951c2a3e901e

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.6.1
    - agate >=1.5.0

test:
  imports:
    - agatestats

about:
  home: http://agate-stats.readthedocs.org/
  license: MIT
  license_family: MIT
  summary: 'agate-stats adds additional statistical methods to agate.'
  # license_file: COPYING - No MANIFEST.in - see https://github.com/wireservice/agate-stats/pull/17
  doc_url: http://agate-stats.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-stats

extra:
  recipe-maintainers:
    - pmlandwehr
