travis:
  secure:
    BINSTAR_TOKEN: EN/BxwEPKunwOmaJui/kUwk1Y+/cAyroUUXELlCgbqorAWhLyNdEJBFYG/+wdKL2tyuXUtBesJQqNLh2jCU9fS+qF2cve5kD9EnMQuNTwQekqkvnHVOVFjOr+8n/CdLQlO/dMAgtJAAUH5vb8O8uEcZxZQoYfZZd6QggVU9b+qWPrNboknxuC/97vvCftG/KnbE84yNZALV/imw61ZRXS50nsyvHbp3NJ89P2VJ+XWJD+7xk+34BiwZFqMT5kH8+6e/7I0Fk0aJdNZKgOfpmThejrRNYVy3EkRseDFM0m3357jY4EJtFthREBjJzdS+IuVK+bFvvewlqMVH0pniyF7NFMt2NGJU5IZjBc0vViYDJ59mGpI66bPuGkL0EWu+9SBUt4QFBO4oVAvIFQlfXUxtMsWouqZEAHOHH+dkYEIFOGmc+zp5TSIfBAkm2toiPWYJ5/j9hqJe54PBJUKy82q9QKsWOW98mHXoKA5MXCNIUKydwR2mXdbIpHYTuc6Nf7tOoTv74AWd07khGluVcleGa1dokaXfJkiVnD/gXvlU0uAz5AeDaEwTsNOqG7aFk/Nd1VilgvVhDV0iqi6LonvStgNGunpT6IDbtWTKLnACmSFIDfmus0xrTqG/Yj9GzMjrMhBU74ZZA2WF9G2senkFrb1yBx+Tfu4GQtu0LooU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
