travis:
  secure:
    BINSTAR_TOKEN: haJL3gPtQKZZsD/lEvcslfOWcFEiuKsHAI3sp/E8AwT94A/vUwyV6MZu4ah7FRwS0HkDQMGXab7ZXn8LFx2uJG4iBuP3NbRh5tUP3PhOe+USfHpOpo3h6zGlt/TOrvLye2tNAIDy2i9y3NfJFF0WcdNwR3LRqWHTiyTN3iFliF/ann6OaQdc9JdxNCPi+ETEob5rxlwoPFAhJrtg5rz0ldkhP+Fi0hdb/F14KyoL4vVg/BRBaOV1HdL6UC0ICsIM+1J7jC8IaUpQCAQLUA1NibgPqtWGcAw+U7GGaVouDl0SKq959WV/khqBlcJVp3AtruOqYAt+P6Z+W04Zood8gZCFrOdrbJ810hWYScpfT4sjgU0iQUKB62Ki/3C/lCHWTCLz6pG7l94AqVAZpcxNIP07lSHo3I6iWHGAKdGB+wMcN4SWK33TEwkc+jg3wdOjHNyWGNGG1pzJWnWy3jz8//xPQUwPr8J6UASTzSXrcUjUF0yiwZ+UPVvNxDBy848pUehwQ8ttKgeHJdongc7It59yFHXXJLcr+0OGK1WgF0K5LpHtpm6cynEXVu+8ZSZfNcJBy3tGs7Lntkp3IIUQir947ZRj4qz4Fts6hynJk8ht/j9vmF/tGd5SfQ4C31woAPH+GADDjVXysdnGjjKqlWMavg03xJuHIPrKdeiGRE8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
